sudo: false
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - python: 3.6
      env: TOXENV=check_readme
    - python: 3.6
      env: TOXENV=pre_commit

install:
  - pip install tox-travis
  - pip install codecov

script:
  - tox

after_success:
  - codecov
